# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(576, 563)
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(30, 90, 511, 441))
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 70, 121, 16))
        self.label.setObjectName("label")
        self.pushButton_create = QtWidgets.QPushButton(Form)
        self.pushButton_create.setGeometry(QtCore.QRect(230, 40, 81, 31))
        self.pushButton_create.setObjectName("pushButton_create")
        self.pushButton_delete = QtWidgets.QPushButton(Form)
        self.pushButton_delete.setGeometry(QtCore.QRect(330, 42, 81, 31))
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.pushButton_join = QtWidgets.QPushButton(Form)
        self.pushButton_join.setGeometry(QtCore.QRect(440, 40, 81, 31))
        self.pushButton_join.setObjectName("pushButton_join")
        self.pushButton_update = QtWidgets.QPushButton(Form)
        self.pushButton_update.setGeometry(QtCore.QRect(40, 20, 91, 31))
        self.pushButton_update.setObjectName("pushButton_update")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Список серверов"))
        self.pushButton_create.setText(_translate("Form", "создать"))
        self.pushButton_delete.setText(_translate("Form", "удалить"))
        self.pushButton_join.setText(_translate("Form", "Войти"))
        self.pushButton_update.setText(_translate("Form", "Обновить"))
