# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen3.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(753, 621)
        self.pushButton_color = QtWidgets.QPushButton(Form)
        self.pushButton_color.setGeometry(QtCore.QRect(620, 50, 75, 23))
        self.pushButton_color.setObjectName("pushButton_color")
        self.pushButton_save = QtWidgets.QPushButton(Form)
        self.pushButton_save.setGeometry(QtCore.QRect(620, 290, 75, 23))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_exit = QtWidgets.QPushButton(Form)
        self.pushButton_exit.setGeometry(QtCore.QRect(620, 550, 81, 31))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setEnabled(True)
        self.graphicsView.setGeometry(QtCore.QRect(50, 30, 551, 551))
        self.graphicsView.setObjectName("graphicsView")
        self.label_color = QtWidgets.QLabel(Form)
        self.label_color.setGeometry(QtCore.QRect(640, 100, 41, 41))
        self.label_color.setText("")
        self.label_color.setObjectName("label_color")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_color.setText(_translate("Form", "color"))
        self.pushButton_save.setText(_translate("Form", "save"))
        self.pushButton_exit.setText(_translate("Form", "exit"))
